// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_llamacpp_session_create
SEXP cpp_llamacpp_session_create(std::string model_path, int n_ctx, int n_batch, int n_threads, int n_gpu_layers);
RcppExport SEXP _llamacppR_cpp_llamacpp_session_create(SEXP model_pathSEXP, SEXP n_ctxSEXP, SEXP n_batchSEXP, SEXP n_threadsSEXP, SEXP n_gpu_layersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type model_path(model_pathSEXP);
    Rcpp::traits::input_parameter< int >::type n_ctx(n_ctxSEXP);
    Rcpp::traits::input_parameter< int >::type n_batch(n_batchSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type n_gpu_layers(n_gpu_layersSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_llamacpp_session_create(model_path, n_ctx, n_batch, n_threads, n_gpu_layers));
    return rcpp_result_gen;
END_RCPP
}
// cpp_llamacpp_session_info
Rcpp::List cpp_llamacpp_session_info(SEXP ext);
RcppExport SEXP _llamacppR_cpp_llamacpp_session_info(SEXP extSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ext(extSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_llamacpp_session_info(ext));
    return rcpp_result_gen;
END_RCPP
}
// cpp_llamacpp_session_destroy
bool cpp_llamacpp_session_destroy(SEXP ext);
RcppExport SEXP _llamacppR_cpp_llamacpp_session_destroy(SEXP extSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ext(extSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_llamacpp_session_destroy(ext));
    return rcpp_result_gen;
END_RCPP
}
// cpp_llamacpp_apply_chat_template
std::string cpp_llamacpp_apply_chat_template(SEXP ext, Rcpp::CharacterVector roles, Rcpp::CharacterVector contents, bool add_generation_prompt);
RcppExport SEXP _llamacppR_cpp_llamacpp_apply_chat_template(SEXP extSEXP, SEXP rolesSEXP, SEXP contentsSEXP, SEXP add_generation_promptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ext(extSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type roles(rolesSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type contents(contentsSEXP);
    Rcpp::traits::input_parameter< bool >::type add_generation_prompt(add_generation_promptSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_llamacpp_apply_chat_template(ext, roles, contents, add_generation_prompt));
    return rcpp_result_gen;
END_RCPP
}
// cpp_llamacpp_session_generate
Rcpp::List cpp_llamacpp_session_generate(SEXP ext, std::string prompt, int max_tokens, double temperature, int top_k, double top_p, double min_p, double repeat_penalty, int seed);
RcppExport SEXP _llamacppR_cpp_llamacpp_session_generate(SEXP extSEXP, SEXP promptSEXP, SEXP max_tokensSEXP, SEXP temperatureSEXP, SEXP top_kSEXP, SEXP top_pSEXP, SEXP min_pSEXP, SEXP repeat_penaltySEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ext(extSEXP);
    Rcpp::traits::input_parameter< std::string >::type prompt(promptSEXP);
    Rcpp::traits::input_parameter< int >::type max_tokens(max_tokensSEXP);
    Rcpp::traits::input_parameter< double >::type temperature(temperatureSEXP);
    Rcpp::traits::input_parameter< int >::type top_k(top_kSEXP);
    Rcpp::traits::input_parameter< double >::type top_p(top_pSEXP);
    Rcpp::traits::input_parameter< double >::type min_p(min_pSEXP);
    Rcpp::traits::input_parameter< double >::type repeat_penalty(repeat_penaltySEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_llamacpp_session_generate(ext, prompt, max_tokens, temperature, top_k, top_p, min_p, repeat_penalty, seed));
    return rcpp_result_gen;
END_RCPP
}
// cpp_llamacpp_test_trigger_fatal
std::string cpp_llamacpp_test_trigger_fatal();
RcppExport SEXP _llamacppR_cpp_llamacpp_test_trigger_fatal() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_llamacpp_test_trigger_fatal());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_llamacppR_cpp_llamacpp_session_create", (DL_FUNC) &_llamacppR_cpp_llamacpp_session_create, 5},
    {"_llamacppR_cpp_llamacpp_session_info", (DL_FUNC) &_llamacppR_cpp_llamacpp_session_info, 1},
    {"_llamacppR_cpp_llamacpp_session_destroy", (DL_FUNC) &_llamacppR_cpp_llamacpp_session_destroy, 1},
    {"_llamacppR_cpp_llamacpp_apply_chat_template", (DL_FUNC) &_llamacppR_cpp_llamacpp_apply_chat_template, 4},
    {"_llamacppR_cpp_llamacpp_session_generate", (DL_FUNC) &_llamacppR_cpp_llamacpp_session_generate, 9},
    {"_llamacppR_cpp_llamacpp_test_trigger_fatal", (DL_FUNC) &_llamacppR_cpp_llamacpp_test_trigger_fatal, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_llamacppR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
