# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_llamacpp_session_create <- function(model_path, n_ctx, n_batch, n_threads, n_gpu_layers) {
    .Call(`_llamacppR_cpp_llamacpp_session_create`, model_path, n_ctx, n_batch, n_threads, n_gpu_layers)
}

cpp_llamacpp_session_info <- function(ext) {
    .Call(`_llamacppR_cpp_llamacpp_session_info`, ext)
}

cpp_llamacpp_session_destroy <- function(ext) {
    .Call(`_llamacppR_cpp_llamacpp_session_destroy`, ext)
}

cpp_llamacpp_apply_chat_template <- function(ext, roles, contents, add_generation_prompt) {
    .Call(`_llamacppR_cpp_llamacpp_apply_chat_template`, ext, roles, contents, add_generation_prompt)
}

cpp_llamacpp_session_generate <- function(ext, prompt, max_tokens, temperature, top_k, top_p, min_p, repeat_penalty, seed) {
    .Call(`_llamacppR_cpp_llamacpp_session_generate`, ext, prompt, max_tokens, temperature, top_k, top_p, min_p, repeat_penalty, seed)
}

cpp_llamacpp_test_trigger_fatal <- function() {
    .Call(`_llamacppR_cpp_llamacpp_test_trigger_fatal`)
}

